# Default values for chat-api
replicaCount: 2

image:
  repository: doc-qa-bot/chat-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-secrets
        key: DATABASE_URL
  - name: AWS_REGION
    value: eu-south-1
  - name: BEDROCK_MODEL_ID
    value: anthropic.claude-3-sonnet-20240229-v1:0
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-secrets
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-secrets
        key: AWS_SECRET_ACCESS_KEY
  - name: BEDROCK_API_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-secrets
        key: BEDROCK_API_KEY
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-secrets
        key: API_KEY

# Secret values (should be overridden in production)
secrets:
  apiKey: "changeme"
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  databaseUrl: "postgresql://user:pass@localhost:5432/db"
  bedrockApiKey: ""

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5 