apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  LOG_LEVEL: "INFO"
  API_VERSION: "v1"
  MAX_TOKENS: "4096"
  TEMPERATURE: "0.7"
  TOP_P: "0.9"
  CHUNK_SIZE: "500"
  CHUNK_OVERLAP: "50"
  VECTOR_DIMENSION: "1536"
  SIMILARITY_THRESHOLD: "0.7"
  MAX_CITATIONS: "3" 