apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  LOG_LEVEL: "INFO"
  API_VERSION: "v1"
  CHUNK_SIZE: "500"
  CHUNK_OVERLAP: "50"
  VECTOR_DIMENSION: "1536"
  MAX_FILE_SIZE: "10485760"  # 10MB
  SUPPORTED_FORMATS: "pdf,html,md,txt"
  PROCESSING_TIMEOUT: "300"  # 5 minutes
  BATCH_SIZE: "10"
  RETRY_ATTEMPTS: "3"
  RETRY_DELAY: "5" 