apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  # These values should be overridden in production
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | default "" | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | default "" | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | default "postgresql://user:pass@localhost:5432/db" | quote }}
  BEDROCK_API_KEY: {{ .Values.secrets.bedrockApiKey | default "" | quote }}
  S3_BUCKET_KEY: {{ .Values.secrets.s3BucketKey | default "" | quote }} 